// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: calculator/v1/calculator.proto

package calculatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Add struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Add) Reset() {
	*x = Add{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Add) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Add) ProtoMessage() {}

func (x *Add) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Add.ProtoReflect.Descriptor instead.
func (*Add) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{0}
}

type Sub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sub) Reset() {
	*x = Sub{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sub) ProtoMessage() {}

func (x *Sub) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sub.ProtoReflect.Descriptor instead.
func (*Sub) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{1}
}

type Mul struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mul) Reset() {
	*x = Mul{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mul) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mul) ProtoMessage() {}

func (x *Mul) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mul.ProtoReflect.Descriptor instead.
func (*Mul) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{2}
}

type Div struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Div) Reset() {
	*x = Div{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Div) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Div) ProtoMessage() {}

func (x *Div) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Div.ProtoReflect.Descriptor instead.
func (*Div) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{3}
}

type Add_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Add_Request) Reset() {
	*x = Add_Request{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Add_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Add_Request) ProtoMessage() {}

func (x *Add_Request) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Add_Request.ProtoReflect.Descriptor instead.
func (*Add_Request) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Add_Request) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Add_Request) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type Add_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             int64                  `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Add_Response) Reset() {
	*x = Add_Response{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Add_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Add_Response) ProtoMessage() {}

func (x *Add_Response) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Add_Response.ProtoReflect.Descriptor instead.
func (*Add_Response) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Add_Response) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

type Sub_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sub_Request) Reset() {
	*x = Sub_Request{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sub_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sub_Request) ProtoMessage() {}

func (x *Sub_Request) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sub_Request.ProtoReflect.Descriptor instead.
func (*Sub_Request) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Sub_Request) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Sub_Request) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type Sub_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             int64                  `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sub_Response) Reset() {
	*x = Sub_Response{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sub_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sub_Response) ProtoMessage() {}

func (x *Sub_Response) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sub_Response.ProtoReflect.Descriptor instead.
func (*Sub_Response) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Sub_Response) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

type Mul_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mul_Request) Reset() {
	*x = Mul_Request{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mul_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mul_Request) ProtoMessage() {}

func (x *Mul_Request) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mul_Request.ProtoReflect.Descriptor instead.
func (*Mul_Request) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Mul_Request) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Mul_Request) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type Mul_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             int64                  `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mul_Response) Reset() {
	*x = Mul_Response{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mul_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mul_Response) ProtoMessage() {}

func (x *Mul_Response) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mul_Response.ProtoReflect.Descriptor instead.
func (*Mul_Response) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Mul_Response) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

type Div_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Div_Request) Reset() {
	*x = Div_Request{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Div_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Div_Request) ProtoMessage() {}

func (x *Div_Request) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Div_Request.ProtoReflect.Descriptor instead.
func (*Div_Request) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Div_Request) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Div_Request) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type Div_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             int64                  `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Div_Response) Reset() {
	*x = Div_Response{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Div_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Div_Response) ProtoMessage() {}

func (x *Div_Response) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Div_Response.ProtoReflect.Descriptor instead.
func (*Div_Response) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Div_Response) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

var File_calculator_v1_calculator_proto protoreflect.FileDescriptor

const file_calculator_v1_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1ecalculator/v1/calculator.proto\x12\rcalculator.v1\"F\n" +
	"\x03Add\x1a%\n" +
	"\aRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\x1a\x18\n" +
	"\bResponse\x12\f\n" +
	"\x01c\x18\x01 \x01(\x03R\x01c\"F\n" +
	"\x03Sub\x1a%\n" +
	"\aRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\x1a\x18\n" +
	"\bResponse\x12\f\n" +
	"\x01c\x18\x01 \x01(\x03R\x01c\"F\n" +
	"\x03Mul\x1a%\n" +
	"\aRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\x1a\x18\n" +
	"\bResponse\x12\f\n" +
	"\x01c\x18\x01 \x01(\x03R\x01c\"F\n" +
	"\x03Div\x1a%\n" +
	"\aRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\x1a\x18\n" +
	"\bResponse\x12\f\n" +
	"\x01c\x18\x01 \x01(\x03R\x01c2\x8c\x02\n" +
	"\n" +
	"Calculator\x12>\n" +
	"\x03Add\x12\x1a.calculator.v1.Add.Request\x1a\x1b.calculator.v1.Add.Response\x12>\n" +
	"\x03Sub\x12\x1a.calculator.v1.Sub.Request\x1a\x1b.calculator.v1.Sub.Response\x12>\n" +
	"\x03Mul\x12\x1a.calculator.v1.Mul.Request\x1a\x1b.calculator.v1.Mul.Response\x12>\n" +
	"\x03Div\x12\x1a.calculator.v1.Div.Request\x1a\x1b.calculator.v1.Div.ResponseB\xd0\x01\n" +
	"\x11com.calculator.v1B\x0fCalculatorProtoP\x01ZUgithub.com/lovromazgon/hornet/example/calculator/sdk/proto/calculator/v1;calculatorv1\xa2\x02\x03CXX\xaa\x02\rCalculator.V1\xca\x02\rCalculator\\V1\xe2\x02\x19Calculator\\V1\\GPBMetadata\xea\x02\x0eCalculator::V1b\x06proto3"

var (
	file_calculator_v1_calculator_proto_rawDescOnce sync.Once
	file_calculator_v1_calculator_proto_rawDescData []byte
)

func file_calculator_v1_calculator_proto_rawDescGZIP() []byte {
	file_calculator_v1_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_v1_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_v1_calculator_proto_rawDesc), len(file_calculator_v1_calculator_proto_rawDesc)))
	})
	return file_calculator_v1_calculator_proto_rawDescData
}

var file_calculator_v1_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_calculator_v1_calculator_proto_goTypes = []any{
	(*Add)(nil),          // 0: calculator.v1.Add
	(*Sub)(nil),          // 1: calculator.v1.Sub
	(*Mul)(nil),          // 2: calculator.v1.Mul
	(*Div)(nil),          // 3: calculator.v1.Div
	(*Add_Request)(nil),  // 4: calculator.v1.Add.Request
	(*Add_Response)(nil), // 5: calculator.v1.Add.Response
	(*Sub_Request)(nil),  // 6: calculator.v1.Sub.Request
	(*Sub_Response)(nil), // 7: calculator.v1.Sub.Response
	(*Mul_Request)(nil),  // 8: calculator.v1.Mul.Request
	(*Mul_Response)(nil), // 9: calculator.v1.Mul.Response
	(*Div_Request)(nil),  // 10: calculator.v1.Div.Request
	(*Div_Response)(nil), // 11: calculator.v1.Div.Response
}
var file_calculator_v1_calculator_proto_depIdxs = []int32{
	4,  // 0: calculator.v1.Calculator.Add:input_type -> calculator.v1.Add.Request
	6,  // 1: calculator.v1.Calculator.Sub:input_type -> calculator.v1.Sub.Request
	8,  // 2: calculator.v1.Calculator.Mul:input_type -> calculator.v1.Mul.Request
	10, // 3: calculator.v1.Calculator.Div:input_type -> calculator.v1.Div.Request
	5,  // 4: calculator.v1.Calculator.Add:output_type -> calculator.v1.Add.Response
	7,  // 5: calculator.v1.Calculator.Sub:output_type -> calculator.v1.Sub.Response
	9,  // 6: calculator.v1.Calculator.Mul:output_type -> calculator.v1.Mul.Response
	11, // 7: calculator.v1.Calculator.Div:output_type -> calculator.v1.Div.Response
	4,  // [4:8] is the sub-list for method output_type
	0,  // [0:4] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_v1_calculator_proto_init() }
func file_calculator_v1_calculator_proto_init() {
	if File_calculator_v1_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_v1_calculator_proto_rawDesc), len(file_calculator_v1_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_v1_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_v1_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_v1_calculator_proto_msgTypes,
	}.Build()
	File_calculator_v1_calculator_proto = out.File
	file_calculator_v1_calculator_proto_goTypes = nil
	file_calculator_v1_calculator_proto_depIdxs = nil
}
